default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  wait_timeout: 300
  
development:
  <<: *default
  username:  foodlog_user
  database: foodlog_db
  pool: 2

test:
  <<: *default
  username:  foodlog_user
  database: foodlog_db
  pool: 2

production:
  <<: *default
  username:  foodlog_user
  database: foodlog_db
  pool: 2
